-- Upstream BiLi_PC_Gamer 2c451bf3 (schema 8), extracted from DAO createTable definitions.
CREATE TABLE "Gallery_Tags" ("GID" INTEGER PRIMARY KEY NOT NULL ,"ROWS" TEXT,"ARTIST" TEXT,"COSPLAYER" TEXT,"CHARACTER" TEXT,"FEMALE" TEXT,"GROUP" TEXT,"LANGUAGE" TEXT,"MALE" TEXT,"MISC" TEXT,"MIXED" TEXT,"OTHER" TEXT,"PARODY" TEXT,"RECLASS" TEXT,"CREATE_TIME" INTEGER,"UPDATE_TIME" INTEGER,"LOCATION" TEXT);
CREATE TABLE "DOWNLOADS" ("GID" INTEGER PRIMARY KEY NOT NULL ,"TOKEN" TEXT,"TITLE" TEXT,"TITLE_JPN" TEXT,"THUMB" TEXT,"CATEGORY" INTEGER NOT NULL ,"POSTED" TEXT,"UPLOADER" TEXT,"RATING" REAL NOT NULL ,"SIMPLE_LANGUAGE" TEXT,"STATE" INTEGER NOT NULL ,"LEGACY" INTEGER NOT NULL ,"TIME" INTEGER NOT NULL ,"LABEL" TEXT,"ARCHIVE_URI" TEXT);
CREATE TABLE "DOWNLOAD_LABELS" ("_id" INTEGER PRIMARY KEY ,"LABEL" TEXT,"TIME" INTEGER NOT NULL );
CREATE TABLE "DOWNLOAD_DIRNAME" ("GID" INTEGER PRIMARY KEY NOT NULL ,"DIRNAME" TEXT);
CREATE TABLE "HISTORY" ("GID" INTEGER PRIMARY KEY NOT NULL ,"TOKEN" TEXT,"TITLE" TEXT,"TITLE_JPN" TEXT,"THUMB" TEXT,"CATEGORY" INTEGER NOT NULL ,"POSTED" TEXT,"UPLOADER" TEXT,"RATING" REAL NOT NULL ,"SIMPLE_LANGUAGE" TEXT,"MODE" INTEGER NOT NULL ,"TIME" INTEGER NOT NULL );
CREATE TABLE "QUICK_SEARCH" ("_id" INTEGER PRIMARY KEY ,"NAME" TEXT,"MODE" INTEGER NOT NULL ,"CATEGORY" INTEGER NOT NULL ,"KEYWORD" TEXT,"ADVANCE_SEARCH" INTEGER NOT NULL ,"MIN_RATING" INTEGER NOT NULL ,"PAGE_FROM" INTEGER NOT NULL ,"PAGE_TO" INTEGER NOT NULL ,"TIME" INTEGER NOT NULL );
CREATE TABLE "Black_List" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT ,"BADGAYNAME" TEXT,"REASON" TEXT,"ANGRYWITH" TEXT,"ADD_TIME" TEXT,"MODE" INTEGER);CREATE INDEX IDX_Black_List_BADGAYNAME ON Black_List ("BADGAYNAME");
CREATE TABLE "LOCAL_FAVORITES" ("GID" INTEGER PRIMARY KEY NOT NULL ,"TOKEN" TEXT,"TITLE" TEXT,"TITLE_JPN" TEXT,"THUMB" TEXT,"CATEGORY" INTEGER NOT NULL ,"POSTED" TEXT,"UPLOADER" TEXT,"RATING" REAL NOT NULL ,"SIMPLE_LANGUAGE" TEXT,"TIME" INTEGER NOT NULL );
CREATE TABLE "BOOKMARKS" ("GID" INTEGER PRIMARY KEY NOT NULL ,"TOKEN" TEXT,"TITLE" TEXT,"TITLE_JPN" TEXT,"THUMB" TEXT,"CATEGORY" INTEGER NOT NULL ,"POSTED" TEXT,"UPLOADER" TEXT,"RATING" REAL NOT NULL ,"SIMPLE_LANGUAGE" TEXT,"PAGE" INTEGER NOT NULL ,"TIME" INTEGER NOT NULL );
CREATE TABLE "FILTER" ("_id" INTEGER PRIMARY KEY ,"MODE" INTEGER NOT NULL ,"TEXT" TEXT,"ENABLE" INTEGER);
PRAGMA user_version = 8;
