name: Build

on:
  push:
    branches: [ BiLi_PC_Gamer ]
  pull_request:
    branches: [ BiLi_PC_Gamer ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: android-actions/setup-android@v3
      - run: sdkmanager 'platforms;android-35' 'ndk;28.2.13676358' 'cmake;3.22.1'

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew app:assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./app/build/outputs/apk/
